#spring.jpa.show_sql=true
  #spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57Dialect
#spring.jpa.properties.hibernate.dialect=
  #spring.jpa.properties.hibernate.dialect.storage_engine=innodb
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.Suffix=.html

server:
  port: 8081
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    prefix: classpath:/static/html/
    suffix: .html


  http:
    encoding:
      force: true
      enabled: true
      force-response: true
      charset: UTF-8
      force-request: true

  datasource:
    username: securus
    password: securus1234
    url: jdbc:mysql://localhost:3307/test?useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 110MB

#debug: true
logging:
  config: classpath:log4j2.xml